### ISSUE TITLE
IPNS accessibility monitoring

### ISSUE THREAD

**Issue by guoliu** [thematters/uptime#269]
- [ ] Monitor IPNS accessibility from major gateways for recently published records.
- [ ] Separate monitoring for ordinary users and travelogger holders
- [ ] Notify the team via slack if IPNS records are not accessible, or trigger IPNS refresh automatically

Notes:
* We can reuse the work done by Charlie, most of the functionality should be there: https://www.notion.so/Charlie-Handover-08268c54d7a84ca4b872f141bb7ae81e#3cf1aed8139e459ab381212cf8c351d0

**Comment by guoliu** [comment]
@gary02 we should be able to reuse the test written by Charlie: https://www.notion.so/matterslab/Charlie-Handover-08268c54d7a84ca4b872f141bb7ae81e?pvs=4#3cf1aed8139e459ab381212cf8c351d0

Just need to be sure it is run periodically and we can get a notification if things go wrong.

**Comment by devformatters** [comment]
Pull back to `Upcoming`.

**Comment by gary02** [comment]
![Image](https://user-images.githubusercontent.com/13580441/234307429-d91588a9-e1a4-430c-8f31-f454495d6018.png)

**Comment by gary02** [comment]
![Image](https://user-images.githubusercontent.com/13580441/234441536-ca6bf904-a0fd-4906-9371-47313e7cafdc.png)

**Comment by gary02** [comment]
log location: metabase-server:/home/ec2-user/ipfs-reachability/ipns-monitor.log

**Comment by devformatters** [comment]
Add task about: syncing the latest Traveloggers list

**Comment by gary02** [comment]
see https://github.com/thematters/matters-integration-test/pull/7  close this issue
